### PR TITLE
Create SD card for Nezha

### PR DESCRIPTION
**Pull request by a-v-s**
I have updated the build script to generate two toc1 files, one for lichee rv and one for nezha,
Then I have created two create sd script, one for nezha and one for lichee rv.

The SD cards generated by the nezha script can boot the nezha and the mangopi.

### CODE REVIEW

**Comment by sehraf** [comment]
Thanks!
Though i'd prefer to not duplicate the create sd card script. As long as the only difference is a single file, I'd like to go with a variable and an `if` or `case`.

**Comment by a-v-s** [comment]
Are you thinking about something that is invoked like 
```
./2_create_sd.sh /dev/sda nezha
```
I'll have a look at it

**Comment by sehraf** [comment]
yes, or an option in `consts.sh`

**Comment by a-v-s** [comment]
I've moved the device tree into the consts.sh file

**Pull request merged**
